### ISSUE TITLE
Dune: `make -f Makefile.dune refman-html` fails

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14195]
The wording "There is a programmable error in your configuration file" is a bit odd.  (It's an exception.)

```
$ make -f Makefile.dune refman-html
dune build @refman-html
      coqdep user-contrib/Ltac2/Env.v.d
*** Warning: in file Env.v,
    required library Init matches several files in path
    (found Init.v in ../../theories/Classes and .; used the latter)
      coqdep user-contrib/Ltac2/Ind.v.d
*** Warning: in file Ind.v,
    required library Init matches several files in path
    (found Init.v in ../../theories/Classes and .; used the latter)
         env doc/refman-html (exit 2)
(cd _build/default/doc && /usr/bin/env COQLIB=.. sphinx-build -q -W -b html sphinx refman-html)

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/jfehrle/.local/lib/python3.6/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/home/jfehrle/.local/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "/home/proj/coq/_build/default/doc/sphinx/conf.py", line 38, in <module>
    import coq_config
ModuleNotFoundError: No module named 'coq_config'

Makefile.dune:101: recipe for target 'refman-html' failed
make: *** [refman-html] Error 1
```

**Comment by ejgallego** [comment]
Can you please reproduce from a pristine tree [using `git clean -fxd` may work but of course beware]?

From a pristine tree I cannot reproduce, tho this could well be some windows-specific issue too.

**Comment by jfehrle** [comment]
I run Ubuntu in WSL2, it won't be windows-specific.

**Comment by jfehrle** [comment]
It was the presence of `config/coq_config.py`
